
USE_PROXY = False
SERVER_URL = "0.0.0.0"
SERVER_PORT = 50001
PROXY_URL = "127.0.0.1"
PROXY_PORT = "8080"
ADMIN_USER = "admin"
TEST_USER = "testuser"
DEFAULT_PASSWORD = "pass"
COMMON_PASSWORD = "passw1"
